apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chapar-ingress
  namespace: chapar
  annotations:
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - chapar.example.com
      secretName: chapar-tls
  rules:
    - host: chapar.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chapar-api-svc
                port:
                  number: 80
